version: "3.8"
services:
  db:
    image: postgres:17
    container_name: pnw_spirits_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pnwspirits
      POSTGRES_PASSWORD: pnwspirits_pw
      POSTGRES_DB: pnwspirits_local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
