"use client";

import { useEffect, useId, useMemo, useState } from "react";

import AdminButton from "@/components/admin/AdminButton";
import AdminConfirmDialog from "@/components/admin/AdminConfirmDialog";
import AdminField from "@/components/admin/AdminField";
import { AdminInput, AdminTextarea } from "@/components/admin/AdminInput";
import AdminPageLayout from "@/components/admin/AdminPageLayout";
import AdminStatus from "@/components/admin/AdminStatus";
import type { AdminStatusTone } from "@/components/admin/admin.types";
import { useAdminDraft } from "@/hooks/useAdminDraft";
import { readAdminError, useAdminFetch } from "@/hooks/useAdminFetch";
import styles from "./AdminNewsletterComposer.module.css";

type NewsletterFailure = { subscriberId: number; email: string; error: string };

type NewsletterResponse = {
  status?: string;
  message?: string;
  testRecipient?: string;
  totalSubscribers?: number;
  attempted?: number;
  sent?: number;
  failed?: number;
  failures?: NewsletterFailure[];
  error?: string;
  details?: Array<{ message?: string }>;
};

type NewsletterDraft = {
  subject: string;
  html: string;
  replyTo: string;
};

// UNCHANGED, deliberately. The key is the address of whatever is sitting in
// this admin's browser right now; renaming it would not migrate a draft, it
// would orphan one.
const NEWSLETTER_DRAFT_STORAGE_KEY = "admin-newsletter-composer-draft";

const STATUS_DISMISS_MS = 8000;

// `details[]` is the API's Zod issue list ("Invalid input"), and readAdminError
// does not cover it - that helper reads the `{ error }` string only. Kept local
// and kept uncapped: unlike a free-form `{ error }` body, which can be anything
// an upstream proxy decided to return, these messages are generated by this
// app's own NewsletterSchema and are short single-line strings by construction.
// readAdminError clones the response, so both may read the same one.
//
// EXPORTED FOR ITS TEST, WHICH IS A READER. See resultTone below for the rule.
// The branch worth pinning is the uncapped one: this is the only path in the
// admin that renders server text without readAdminError's safe-shape check,
// and it is safe ONLY because these strings are generated by this app's own
// NewsletterSchema. A test is what holds that reasoning to the code.
export function joinDetailMessages(data: NewsletterResponse | null): string {
  if (!data || !Array.isArray(data.details)) return "";
  return data.details
    .map((detail) => detail.message)
    .filter((message): message is string => Boolean(message))
    .join(", ");
}

/**
 * What tone a COMPLETED send is reported in.
 *
 * The three-way rule this admin runs on is by consequence, not by severity: a
 * failed write is an alarm, a failed read is prose, and a fact that destroyed
 * nothing is neutral. A send result is mostly the third case - it is a report
 * on an operation that finished - so it is not --danger merely because one of
 * its numbers is non-zero. But "nothing reached anybody" is a failed write by
 * any reading, and burying it in a green-adjacent success line would be the
 * composer telling the admin the opposite of what happened.
 *
 * Colour is never the sole carrier either way: the counts below state the
 * outcome in words, which is what makes this mapping an emphasis and not a
 * message of its own.
 *
 * EXPORTED FOR ITS TEST, WHICH IS A READER - AND THE RULE THE OTHER TWO
 * EXPORTS IN THIS FILE POINT AT.
 *
 * The export is not "a test wants it". It is that the `sent === 0` branch is
 * the composer telling the admin the OPPOSITE of what happened: a newsletter
 * that reached nobody, reported in the same treatment as one that reached
 * everybody. Nothing on screen looks broken in that state - the counts are
 * right, the line is calm, and the admin walks away believing the send landed.
 * Only the tone carries the alarm, and only a test carries the tone.
 *
 * These three helpers are otherwise unreachable from a test: they are pure, but
 * they render only after a fetch resolves into state, and this repo's Vitest
 * runs in the node environment with no DOM (see the test file's scope note). So
 * the export IS the coverage, and removing it as "unused" removes the check.
 */
export function resultTone(result: NewsletterResponse): AdminStatusTone {
  const attempted = result.attempted ?? 0;
  const sent = result.sent ?? 0;
  if (attempted === 0) return "info"; // nobody subscribed; nothing was owed
  if (sent === 0) return "error"; // attempted and none landed
  if ((result.failed ?? 0) > 0) return "info"; // partial, and the counts say so
  return "success";
}

// EXPORTED FOR ITS TEST, WHICH IS A READER. See resultTone above for the rule.
// This is the half that states the outcome in WORDS, which is what keeps the
// tone an emphasis rather than the only carrier of the message - so the two
// must agree, and a test comparing them is the only thing that checks they do.
export function describeResult(result: NewsletterResponse): string {
  const attempted = result.attempted ?? 0;
  const sent = result.sent ?? 0;
  if (attempted === 0) {
    return "There are no subscribers yet, so nothing was sent.";
  }
  if (sent === 0) {
    return "The newsletter reached nobody. Every delivery attempt failed.";
  }
  if (sent < attempted) {
    return `Newsletter sent to ${sent} of ${attempted} subscribers.`;
  }
  return `Newsletter sent to all ${sent} subscribers.`;
}

/**
 * EXPORTED FOR ITS TEST, WHICH IS A READER. See resultTone above for the rule.
 *
 * The specimen half of the composer, split out for the same reason `resultTone`
 * and `describeResult` were: inside the screen its only interesting state - a
 * non-empty `html` - is reachable only by typing, and this environment cannot
 * type. As a component taking `html` as a prop, both branches render on demand,
 * so the sandbox below is pinned against MARKUP THAT WAS ACTUALLY PRODUCED
 * rather than against the source text of this file.
 *
 * It is a pure function of `html` and owns nothing else: the caption id is
 * local, the trim is local, and no state or handler crosses the boundary.
 */
export function NewsletterPreview({ html }: { html: string }): React.ReactNode {
  const captionId = useId();
  const trimmedHtml = html.trim();

  return (
    /* NOT the row anatomy, and not warm-dark. Email HTML is light; this
       rectangle is white because a real inbox is white, and the framing is
       what turns it from a hole in the page into a specimen under
       inspection. */
    <section className={styles.preview} aria-labelledby={captionId}>
      <p className={styles.previewCaption} id={captionId}>
        Preview
      </p>
      <div
        className={
          trimmedHtml
            ? `${styles.previewPlate} ${styles.previewPlateFilled}`
            : styles.previewPlate
        }
      >
        {trimmedHtml ? (
          <iframe
            className={styles.previewFrame}
            title="Newsletter HTML preview"
            // EMPTY sandbox, and it is a hard requirement rather than a
            // hardening pass. A srcdoc frame inherits the EMBEDDER's origin,
            // so a <script> in pasted newsletter HTML would run same-origin
            // with this page and could read the admin bearer token straight
            // out of localStorage - the precise payload this repo already
            // sanitises against in blogContentService. Three things make it
            // concrete here: this HTML is routinely pasted from third-party
            // templates, it is re-hydrated from a localStorage draft on
            // mount, and the token sits one getItem away.
            //
            // `sandbox=""` and not "allow-scripts allow-same-origin", which
            // is equivalent to no sandbox at all - together those two flags
            // let the frame reach out and remove its own sandbox attribute.
            // Empty also happens to be the faithful preview: no email
            // client runs JavaScript, so a script that ran here would be
            // showing the admin something no subscriber will ever see.
            sandbox=""
            srcDoc={trimmedHtml}
          />
        ) : (
          <p className={styles.previewEmpty}>
            The rendered email appears here as you type.
          </p>
        )}
      </div>
    </section>
  );
}

export default function AdminNewsletterComposer(): React.ReactNode {
  const adminFetch = useAdminFetch();

  const [subject, setSubject] = useState("");
  const [html, setHtml] = useState("");
  const [replyTo, setReplyTo] = useState("");
  const [sendingAction, setSendingAction] = useState<"all" | "test" | null>(
    null,
  );
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [result, setResult] = useState<NewsletterResponse | null>(null);
  /** The broadcast is awaiting confirmation. It is a boolean rather than a
   *  record because there is only ever one thing being sent: whatever is in the
   *  form right now. */
  const [pendingSend, setPendingSend] = useState(false);

  const { draft, hydrated, save } = useAdminDraft<Partial<NewsletterDraft>>(
    NEWSLETTER_DRAFT_STORAGE_KEY,
  );
  const [isDraftApplied, setIsDraftApplied] = useState(false);

  // Seeds the form from storage exactly once, on the first render after the
  // client read lands. The `isDraftApplied` latch is what makes it once: `draft`
  // is a live subscription and another tab writing this key would otherwise
  // re-seed the form out from under whoever is typing in this one.
  //
  // Each field is still type-checked individually. `T` in useAdminDraft is a
  // compile-time shape only - what is actually in storage was written by some
  // earlier version of this component - so the hook cannot vouch for it and
  // this is the boundary that must.
  useEffect(() => {
    if (!hydrated || isDraftApplied) return;
    /* eslint-disable react-hooks/set-state-in-effect */
    setIsDraftApplied(true);
    if (!draft) return;
    if (typeof draft.subject === "string") setSubject(draft.subject);
    if (typeof draft.html === "string") setHtml(draft.html);
    if (typeof draft.replyTo === "string") setReplyTo(draft.replyTo);
    /* eslint-enable react-hooks/set-state-in-effect */
  }, [hydrated, isDraftApplied, draft]);

  // Gated on the seed having run, not only on `save`'s own hydration guard.
  // Both are needed and they stop different things: the hook's guard stops a
  // pre-hydration write, and this stops the one-render window between hydration
  // and the seed landing, where the form state is still empty and this effect
  // would write those blanks over the stored draft.
  useEffect(() => {
    if (!isDraftApplied) return;
    save({ subject, html, replyTo });
  }, [isDraftApplied, subject, html, replyTo, save]);

  useEffect(() => {
    if (!success) return;
    const timeoutId = window.setTimeout(
      () => setSuccess(""),
      STATUS_DISMISS_MS,
    );
    return () => window.clearTimeout(timeoutId);
  }, [success]);

  useEffect(() => {
    if (!error) return;
    const timeoutId = window.setTimeout(() => setError(""), STATUS_DISMISS_MS);
    return () => window.clearTimeout(timeoutId);
  }, [error]);

  const trimmedSubject = subject.trim();
  const trimmedHtml = html.trim();
  const canSubmit =
    trimmedSubject.length > 0 && trimmedHtml.length > 0 && !sendingAction;

  const resultBlock = useMemo(() => {
    if (!result || result.status === "test_sent") return null;
    return { tone: resultTone(result), summary: describeResult(result) };
  }, [result]);

  // Submitting the form OPENS the confirmation; it does not send. The gate is
  // now structural rather than a branch inside the sender: `sendNewsletter`
  // has exactly one caller for mode "all", and it is `confirmSendToAll` below.
  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    // The submit control is already disabled while `canSubmit` is false, so
    // this is unreachable in a pointer flow. It is here because the dialog is a
    // new intermediate state and an empty draft must not be able to open it -
    // a confirmation for a send that the server would reject is a prompt that
    // teaches the admin to dismiss prompts.
    if (!canSubmit) return;
    setPendingSend(true);
  }

  async function confirmSendToAll() {
    try {
      await sendNewsletter("all");
    } finally {
      // Closed on every outcome. The result - sent, partial, or failed - is
      // reported on the page, in the status region below the form, and a
      // dialog left open would be sitting on top of the answer.
      setPendingSend(false);
    }
  }

  async function sendNewsletter(mode: "all" | "test") {
    /**
     * THE HIGHEST-CONSEQUENCE RE-ENTRANCY GUARD IN THIS ADMIN, and it is owed
     * now that the control's inertness is ours rather than the browser's.
     *
     * Both send controls used to be `disabled` while `sendingAction` was set -
     * `canSubmit` includes `!sendingAction`, and the dialog's confirm carries
     * `busy` - so a second activation was refused by the browser and this
     * function could not be re-entered. A busy AdminButton is now
     * `aria-disabled`: focusable, and inert only because AdminButton cancels
     * the activation. That is correct and measured, but what it stands between
     * is a second POST /api/admin/newsletter, which is a second copy of the
     * same newsletter in every subscriber's inbox and cannot be recalled.
     *
     * Stated here rather than at the two call sites because there are two -
     * the test button and confirmSendToAll - and one of them opens a dialog
     * first, so the guard must sit where the request is, not where the press
     * is. handleSubmit's `if (!canSubmit) return` is the gate on OPENING that
     * dialog and is a different question.
     */
    if (sendingAction) return;
    setSendingAction(mode);
    setError("");
    setSuccess("");
    setResult(null);

    const failureMessage =
      mode === "test"
        ? "Failed to send test email"
        : "Failed to send newsletter";

    try {
      // adminFetch signs the request, and on 401/403 it ends the session and
      // lets AdminAuthGate issue the one redirect. It does NOT stop this
      // handler, so the branch below is a plain !res.ok - a status check here
      // would be a second, divergent answer to a question the hook settled.
      const res = await adminFetch("/api/admin/newsletter", {
        method: "POST",
        json: {
          mode,
          subject: trimmedSubject,
          html,
          replyTo: replyTo.trim() || undefined,
        },
      });

      if (!res.ok) {
        const message = await readAdminError(res, failureMessage);
        const data = (await res
          .json()
          .catch(() => null)) as NewsletterResponse | null;
        setError(joinDetailMessages(data) || message);
        return;
      }

      const data = (await res.json()) as NewsletterResponse;
      setResult(data);
      if (mode === "test") {
        setSuccess(
          `Test email sent to ${data.testRecipient ?? "the configured test recipient"}.`,
        );
      }
    } catch {
      setError(failureMessage);
    } finally {
      setSendingAction(null);
    }
  }

  return (
    <AdminPageLayout
      heading="Send Newsletter"
      intro="Compose the email, send yourself a test, then broadcast it to every subscriber."
    >
      {/* THREE BLOCKS, AND THE ORDER IS THE MOBILE COMPOSITION. Below the seam
          there is one column, so DOM order IS reading order, and the order is
          source -> specimen -> commit: the admin writes the email, looks at
          what it renders into, and only then reaches the control that cannot be
          recalled. It used to be source -> commit -> specimen, which put "Send
          to all subscribers" above the only thing that could have talked the
          admin out of pressing it, and left the preview stranded below the
          bottom of the task.

          The preview is INSIDE the form, which is what makes that order
          possible without a CSS `order` trick. The send controls have to stay
          inside the form element to submit it, so the only way to get the
          preview between the fields and the actions is to put it there in the
          DOM - and the reordering must not be visual-only, because SC 1.3.2
          asks that a meaningful sequence survive in the DOM and a keyboard user
          tabbing from the textarea would otherwise still reach Send before the
          preview. A <section> is flow content, so a form may contain one, and
          an unnamed <form> is not exposed as a landmark, so this nests no
          regions. Above the seam grid-template-areas puts it back in column 2. */}
      <form className={styles.composer} onSubmit={handleSubmit}>
        <div className={styles.fields}>
          <AdminField label="Subject" required>
            {(control) => (
              <AdminInput
                {...control}
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                maxLength={160}
                required
              />
            )}
          </AdminField>

          <AdminField
            label="Reply-to"
            hint="Optional. Where a subscriber's reply lands."
          >
            {(control) => (
              <AdminInput
                {...control}
                type="email"
                value={replyTo}
                onChange={(e) => setReplyTo(e.target.value)}
                placeholder="hello@example.com"
                autoComplete="email"
              />
            )}
          </AdminField>

          <AdminField
            label="HTML content"
            hint="Paste the email's HTML. It renders in the preview as you type."
            required
          >
            {(control) => (
              <AdminTextarea
                {...control}
                className={styles.htmlInput}
                value={html}
                onChange={(e) => setHtml(e.target.value)}
                placeholder="<p>Hello from the Pacific Northwest…</p>"
                spellCheck={false}
                required
              />
            )}
          </AdminField>
        </div>

        <NewsletterPreview html={html} />

        <div className={styles.foot}>
          {error ? <AdminStatus tone="error">{error}</AdminStatus> : null}

          {success ? <AdminStatus tone="success">{success}</AdminStatus> : null}

          {resultBlock && result ? (
            <AdminStatus tone={resultBlock.tone}>
              {resultBlock.summary}
              <dl className={styles.counts}>
                <div className={styles.count}>
                  <dt>Subscribers</dt>
                  <dd>{result.totalSubscribers ?? 0}</dd>
                </div>
                <div className={styles.count}>
                  <dt>Attempted</dt>
                  <dd>{result.attempted ?? 0}</dd>
                </div>
                <div className={styles.count}>
                  <dt>Sent</dt>
                  <dd>{result.sent ?? 0}</dd>
                </div>
                <div className={styles.count}>
                  <dt>Failed</dt>
                  <dd>{result.failed ?? 0}</dd>
                </div>
              </dl>
              {result.failures && result.failures.length > 0 ? (
                <span className={styles.failureExample}>
                  First failure: {result.failures[0].email} (
                  {result.failures[0].error})
                </span>
              ) : null}
            </AdminStatus>
          ) : null}

          {/* The rehearsal comes before the commitment, left to right, and the
              irreversible control is last for the same reason Delete is last in
              a row: the pointer travelling the cluster reaches it only on
              purpose. flex-wrap is on .actions - two 40px controls side by side
              overflow a 390px viewport. */}
          <div className={styles.actions}>
            <AdminButton
              onClick={() => void sendNewsletter("test")}
              disabled={!canSubmit}
              busy={sendingAction === "test"}
            >
              {sendingAction === "test" ? "Sending test…" : "Send test email"}
            </AdminButton>
            <AdminButton
              type="submit"
              tone="primary"
              disabled={!canSubmit}
              busy={sendingAction === "all"}
            >
              {sendingAction === "all" ? "Sending…" : "Send to all subscribers"}
            </AdminButton>
          </div>
        </div>
      </form>

      {/* THE ONE IRREVERSIBLE ACTION IN THIS ADMIN THAT DESTROYS NOTHING, and
          it still takes the --danger treatment. The rule the shared dialog
          states is about the moment of COMMITMENT, not about destruction: the
          alarm colour belongs on the control past which there is no going
          back, and it is the only --danger on screen when it is showing. A
          send cannot be recalled from an inbox any more than a deleted row can
          be recovered, and it reaches every subscriber rather than one record,
          so styling it as an ordinary primary would be this composer telling
          the admin that the largest action on the screen is a routine one.

          NO SUBSCRIBER COUNT IN THE MESSAGE, deliberately. The only count this
          component ever holds is `result.totalSubscribers`, which arrives with
          the response to a PREVIOUS send - it describes the list as it was,
          not as it is. A number stated here would be right often enough to be
          trusted and stale exactly when it mattered. */}
      <AdminConfirmDialog
        isOpen={pendingSend}
        heading="Send to all subscribers"
        message={
          <>
            <strong>{trimmedSubject}</strong> will be emailed to every
            subscriber on the list. A newsletter cannot be recalled once it has
            been sent.
          </>
        }
        confirmLabel="Send to all subscribers"
        confirmBusyLabel="Sending…"
        // Not "Cancel": the way out of this dialog is back to the draft, which
        // is intact and still in the form behind it.
        cancelLabel="Keep editing"
        busy={sendingAction === "all"}
        onConfirm={() => void confirmSendToAll()}
        onCancel={() => setPendingSend(false)}
      />
    </AdminPageLayout>
  );
}
